"""Add table settings

Revision ID: 91387fa10feb
Revises: a85d09078e77
Create Date: 2024-10-24 23:12:28.309358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91387fa10feb'
down_revision: Union[str, None] = 'a85d09078e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('buy_slippage', sa.Float(), nullable=True),
    sa.Column('sell_slippage', sa.Float(), nullable=True),
    sa.Column('extra_confirmation', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=True)
    op.drop_column('users', 'extra_confirmation')
    op.drop_column('users', 'buy_slippage')
    op.drop_column('users', 'sell_slippage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sell_slippage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('buy_slippage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('extra_confirmation', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    # ### end Alembic commands ###
