"""Initial

Revision ID: 6867812a5fe7
Revises: 
Create Date: 2024-11-13 00:04:55.380420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6867812a5fe7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_table('add',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('button_text', sa.String(length=32), nullable=False),
    sa.Column('link_text', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_add_id'), 'add', ['id'], unique=False)
    op.create_table('partners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('inviteCode', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('inviteCode')
    )
    op.create_index(op.f('ix_partners_inviteCode'), 'partners', ['inviteCode'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('chatId', sa.Text(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_table('daily_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('users_entered', sa.Integer(), nullable=False),
    sa.Column('new_users_entered', sa.Integer(), nullable=False),
    sa.Column('partner_users_entered', sa.Integer(), nullable=False),
    sa.Column('reffered_users_entered', sa.Integer(), nullable=False),
    sa.Column('connected_wallets', sa.Integer(), nullable=False),
    sa.Column('farm_started', sa.Integer(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_activities_id'), 'daily_activities', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('isPremium', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('lastLogin', sa.DateTime(), nullable=True),
    sa.Column('partner', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['partner'], ['partners.inviteCode'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('age', sa.DOUBLE_PRECISION(), nullable=False),
    sa.Column('inviteCode', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('heSeeWelcomeScreen', sa.Boolean(), nullable=False),
    sa.Column('reffers_checked', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inviteCode')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=True)
    op.create_table('settings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('buy_slippage', sa.Float(), nullable=False),
    sa.Column('sell_slippage', sa.Float(), nullable=False),
    sa.Column('extra_confirmation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_id'), 'settings', ['id'], unique=True)
    op.create_table('wallets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('coins', sa.Integer(), nullable=False),
    sa.Column('tickets', sa.Integer(), nullable=False),
    sa.Column('wallet_address', sa.Text(), nullable=True),
    sa.Column('wallet_type', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=True)
    op.create_table('_AccountToTask',
    sa.Column('A', sa.BigInteger(), nullable=False),
    sa.Column('B', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['A'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['B'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('A', 'B')
    )
    op.create_table('farms',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('wallet', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wallet'], ['wallets.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'wallet'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_farms_wallet'), 'farms', ['wallet'], unique=False)
    op.create_table('reffers_accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('earned_coins', sa.Integer(), nullable=False),
    sa.Column('earned_tickets', sa.Integer(), nullable=False),
    sa.Column('oneWhoInvited', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['oneWhoInvited'], ['accounts.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reffers_accounts_id'), 'reffers_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_reffers_accounts_oneWhoInvited'), 'reffers_accounts', ['oneWhoInvited'], unique=False)
    op.create_table('rewards',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('lastReward', sa.DateTime(), nullable=True),
    sa.Column('coinsCount', sa.Integer(), nullable=False),
    sa.Column('ticketCount', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['wallets.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solana_wallets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('wallet', sa.BigInteger(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('encrypted_private_key', sa.LargeBinary(), nullable=False),
    sa.Column('number_of_trades', sa.Integer(), nullable=False),
    sa.Column('number_of_snipes', sa.Integer(), nullable=False),
    sa.Column('trading_points_earned', sa.Integer(), nullable=False),
    sa.Column('commision_earned', sa.BigInteger(), nullable=False),
    sa.Column('entries', sa.Integer(), nullable=False),
    sa.Column('total_volume', sa.Float(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wallet'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solana_wallets_public_key'), 'solana_wallets', ['public_key'], unique=False)
    op.create_index(op.f('ix_solana_wallets_wallet'), 'solana_wallets', ['wallet'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('wallet', sa.BigInteger(), nullable=False),
    sa.Column('token_address', sa.Text(), nullable=False),
    sa.Column('sol_amount', sa.Float(), nullable=False),
    sa.Column('slippage', sa.Float(), nullable=False),
    sa.Column('mev_protection', sa.Boolean(), nullable=False),
    sa.Column('gas', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wallet'], ['solana_wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_wallet'), 'orders', ['wallet'], unique=False)
    op.create_table('swaps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('wallet', sa.BigInteger(), nullable=False),
    sa.Column('input_mint', sa.Text(), nullable=False),
    sa.Column('output_mint', sa.Text(), nullable=False),
    sa.Column('input_amount', sa.BigInteger(), nullable=False),
    sa.Column('output_amount', sa.BigInteger(), nullable=False),
    sa.Column('txn_sig', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wallet'], ['solana_wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swaps_wallet'), 'swaps', ['wallet'], unique=False)
    op.create_table('withdraws',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('wallet', sa.BigInteger(), nullable=False),
    sa.Column('from_pubkey', sa.Text(), nullable=False),
    sa.Column('to_pubkey', sa.Text(), nullable=False),
    sa.Column('lamports', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wallet'], ['solana_wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdraws_wallet'), 'withdraws', ['wallet'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_withdraws_wallet'), table_name='withdraws')
    op.drop_table('withdraws')
    op.drop_index(op.f('ix_swaps_wallet'), table_name='swaps')
    op.drop_table('swaps')
    op.drop_index(op.f('ix_orders_wallet'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_solana_wallets_wallet'), table_name='solana_wallets')
    op.drop_index(op.f('ix_solana_wallets_public_key'), table_name='solana_wallets')
    op.drop_table('solana_wallets')
    op.drop_table('rewards')
    op.drop_index(op.f('ix_reffers_accounts_oneWhoInvited'), table_name='reffers_accounts')
    op.drop_index(op.f('ix_reffers_accounts_id'), table_name='reffers_accounts')
    op.drop_table('reffers_accounts')
    op.drop_index(op.f('ix_farms_wallet'), table_name='farms')
    op.drop_table('farms')
    op.drop_table('_AccountToTask')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_settings_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_daily_activities_id'), table_name='daily_activities')
    op.drop_table('daily_activities')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_partners_inviteCode'), table_name='partners')
    op.drop_table('partners')
    op.drop_index(op.f('ix_add_id'), table_name='add')
    op.drop_table('add')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
