"""Add solana wallet

Revision ID: c4649acc2f62
Revises: 2b6508c9bc66
Create Date: 2024-09-29 19:21:01.467564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4649acc2f62'
down_revision: Union[str, None] = '2b6508c9bc66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solana_wallets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('wallet', sa.BigInteger(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('encrypted_private_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wallet'], ['wallets.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'wallet'),
    sa.UniqueConstraint('encrypted_private_key'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('public_key')
    )
    op.create_index(op.f('ix_solana_wallets_wallet'), 'solana_wallets', ['wallet'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solana_wallets_wallet'), table_name='solana_wallets')
    op.drop_table('solana_wallets')
    # ### end Alembic commands ###
