"""commision earned to reffer account

Revision ID: 33ec4a351ea2
Revises: ebe5e30bc9fb
Create Date: 2024-11-13 21:26:09.128948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33ec4a351ea2'
down_revision: Union[str, None] = 'ebe5e30bc9fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reffers_accounts', sa.Column('earned_sol', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reffers_accounts', 'earned_sol')
    # ### end Alembic commands ###
