"""create order

Revision ID: 5120c2886c8b
Revises: 5d83a413b5a5
Create Date: 2024-10-27 15:17:19.582334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5120c2886c8b'
down_revision: Union[str, None] = '5d83a413b5a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('wallet', sa.BigInteger(), nullable=False),
    sa.Column('token_address', sa.Text(), nullable=False),
    sa.Column('sol_amount', sa.Float(), nullable=False),
    sa.Column('slippage', sa.Float(), nullable=False),
    sa.Column('mev_protection', sa.Boolean(), nullable=False),
    sa.Column('gas', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wallet'], ['solana_wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_wallet'), 'orders', ['wallet'], unique=False)
    op.add_column('solana_wallets', sa.Column('entries', sa.INTEGER(), autoincrement=False, nullable=True, default=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solana_wallets', 'entries')
    op.drop_index(op.f('ix_orders_wallet'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###