"""Update withdraw

Revision ID: a85d09078e77
Revises: 817b25374f5c
Create Date: 2024-10-20 23:13:12.535621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a85d09078e77'
down_revision: Union[str, None] = '817b25374f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdraws', sa.Column('from_pubkey', sa.Text(), nullable=False))
    op.add_column('withdraws', sa.Column('to_pubkey', sa.Text(), nullable=False))
    op.add_column('withdraws', sa.Column('lamports', sa.BigInteger(), nullable=False))
    op.drop_column('withdraws', 'receiver_address')
    op.drop_column('withdraws', 'mint')
    op.drop_column('withdraws', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdraws', sa.Column('amount', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('withdraws', sa.Column('mint', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('withdraws', sa.Column('receiver_address', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('withdraws', 'lamports')
    op.drop_column('withdraws', 'to_pubkey')
    op.drop_column('withdraws', 'from_pubkey')
    # ### end Alembic commands ###
