"""Update account

Revision ID: 2f143701176d
Revises: c4649acc2f62
Create Date: 2024-10-03 22:06:02.616187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f143701176d'
down_revision: Union[str, None] = 'c4649acc2f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_solana_wallets_wallet', table_name='solana_wallets')
    op.drop_table('solana_wallets')
    op.add_column('accounts', sa.Column('reffers_checked', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'reffers_checked')
    op.create_table('solana_wallets',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('wallet', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('public_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('encrypted_private_key', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['wallet'], ['wallets.id'], name='solana_wallets_wallet_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'wallet', name='solana_wallets_pkey'),
    sa.UniqueConstraint('encrypted_private_key', name='solana_wallets_encrypted_private_key_key'),
    sa.UniqueConstraint('id', name='solana_wallets_id_key'),
    sa.UniqueConstraint('public_key', name='solana_wallets_public_key_key')
    )
    op.create_index('ix_solana_wallets_wallet', 'solana_wallets', ['wallet'], unique=False)
    # ### end Alembic commands ###
