"""Add levels

Revision ID: ebe5e30bc9fb
Revises: 5120c2886c8b
Create Date: 2024-11-07 22:30:38.015068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebe5e30bc9fb'
down_revision: Union[str, None] = '5120c2886c8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('solana_wallets', sa.Column('total_volume', sa.Float(), nullable=True))
    op.add_column('solana_wallets', sa.Column('level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('solana_wallets', 'level')
    op.drop_column('solana_wallets', 'total_volume')
    # ### end Alembic commands ###
