"""Add solana wallet

Revision ID: 0c6a58e58e2f
Revises: a445a410f486
Create Date: 2024-10-16 20:11:09.497781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6a58e58e2f'
down_revision: Union[str, None] = 'a445a410f486'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solana_wallets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('wallet', sa.BigInteger(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('encrypted_private_key', sa.LargeBinary(), nullable=False),
    sa.Column('number_of_trades', sa.Integer(), nullable=False),
    sa.Column('number_of_snipes', sa.Integer(), nullable=False),
    sa.Column('trading_points_earned', sa.Integer(), nullable=False),
    sa.Column('commision_earned', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wallet'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solana_wallets_public_key'), 'solana_wallets', ['public_key'], unique=False)
    op.create_index(op.f('ix_solana_wallets_wallet'), 'solana_wallets', ['wallet'], unique=False)
    op.create_table('swaps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('wallet', sa.BigInteger(), nullable=False),
    sa.Column('input_mint', sa.Text(), nullable=False),
    sa.Column('output_mint', sa.Text(), nullable=False),
    sa.Column('input_amount', sa.BigInteger(), nullable=False),
    sa.Column('output_amount', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wallet'], ['solana_wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swaps_wallet'), 'swaps', ['wallet'], unique=False)
    op.create_table('withdraws',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('wallet', sa.BigInteger(), nullable=False),
    sa.Column('mint', sa.Text(), nullable=False),
    sa.Column('receiver_address', sa.Text(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['wallet'], ['solana_wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdraws_wallet'), 'withdraws', ['wallet'], unique=False)
    op.add_column('users', sa.Column('buy_slippage', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('sell_slippage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sell_slippage')
    op.drop_column('users', 'buy_slippage')
    op.drop_index(op.f('ix_withdraws_wallet'), table_name='withdraws')
    op.drop_table('withdraws')
    op.drop_index(op.f('ix_swaps_wallet'), table_name='swaps')
    op.drop_table('swaps')
    op.drop_index(op.f('ix_solana_wallets_wallet'), table_name='solana_wallets')
    op.drop_index(op.f('ix_solana_wallets_public_key'), table_name='solana_wallets')
    op.drop_table('solana_wallets')
    # ### end Alembic commands ###
