"""UPDATE

Revision ID: a445a410f486
Revises: 2f143701176d
Create Date: 2024-10-06 23:51:23.223921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a445a410f486'
down_revision: Union[str, None] = '2f143701176d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_table('daily_activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('users_entered', sa.Integer(), nullable=False),
    sa.Column('new_users_entered', sa.Integer(), nullable=False),
    sa.Column('partner_users_entered', sa.Integer(), nullable=False),
    sa.Column('reffered_users_entered', sa.Integer(), nullable=False),
    sa.Column('connected_wallets', sa.Integer(), nullable=False),
    sa.Column('farm_started', sa.Integer(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_activities_id'), 'daily_activities', ['id'], unique=False)
    op.add_column('users', sa.Column('lastLogin', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastLogin')
    op.drop_index(op.f('ix_daily_activities_id'), table_name='daily_activities')
    op.drop_table('daily_activities')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
